from PySide2 import QtCore, QtGui, QtWidgets
import shiboken2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 600)
        Dialog.setSizeIncrement(QtCore.QSize(50, 50))
        Dialog.setBaseSize(QtCore.QSize(50, 50))
        self.TEXT = QtWidgets.QTextBrowser(Dialog)
        self.TEXT.setGeometry(QtCore.QRect(10, 470, 181, 111))
        self.TEXT.setObjectName("TEXT")
        self.imgLabel = QtWidgets.QLabel(Dialog)
        self.imgLabel.setGeometry(QtCore.QRect(200, 120, 590, 470))
        self.imgLabel.setAutoFillBackground(False)
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.CAPTURE = QtWidgets.QPushButton(Dialog)
        self.CAPTURE.setGeometry(QtCore.QRect(10, 130, 181, 91))
        self.CAPTURE.setObjectName("CAPTURE")
        self.imgLabel_2 = QtWidgets.QLabel(Dialog)
        self.imgLabel_2.setGeometry(QtCore.QRect(0, 0, 1922, 41))
        self.imgLabel_2.setAutoFillBackground(False)
        self.imgLabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel_2.setText("")
        self.imgLabel_2.setPixmap(QtGui.QPixmap("ngang1.png"))
        self.imgLabel_2.setObjectName("imgLabel_2")
        self.NEXT_2 = QtWidgets.QPushButton(Dialog)
        self.NEXT_2.setGeometry(QtCore.QRect(0, 40, 201, 81))
        self.NEXT_2.setObjectName("NEXT_2")
        self.NEXT_4 = QtWidgets.QPushButton(Dialog)
        self.NEXT_4.setGeometry(QtCore.QRect(200, 40, 191, 81))
        self.NEXT_4.setObjectName("NEXT_4")
        self.NEXT_5 = QtWidgets.QPushButton(Dialog)
        self.NEXT_5.setGeometry(QtCore.QRect(390, 40, 191, 81))
        self.NEXT_5.setObjectName("NEXT_5")
        self.NEXT_3 = QtWidgets.QPushButton(Dialog)
        self.NEXT_3.setGeometry(QtCore.QRect(10, 230, 181, 101))
        self.NEXT_3.setObjectName("NEXT_3")
        self.NEXT_7 = QtWidgets.QPushButton(Dialog)
        self.NEXT_7.setGeometry(QtCore.QRect(580, 40, 181, 81))
        self.NEXT_7.setObjectName("NEXT_7")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 410, 151, 32))
        self.checkBox_5.setSizeIncrement(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(20, 340, 161, 51))
        self.spinBox.setObjectName("spinBox")

        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(790, 20, 230, 570))
        self.listWidget.setObjectName("ListWidgetItem")
        self.listWidget.setIconSize(QtCore.QSize(188, 190))
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)


        it = QtWidgets.QListWidgetItem(self.listWidget)
        it.setIcon(QtGui.QIcon("3.png"))
        it1 = QtWidgets.QListWidgetItem(self.listWidget)
        it1.setIcon(QtGui.QIcon("demo.png"))
        it2 = QtWidgets.QListWidgetItem(self.listWidget)
        it2.setIcon(QtGui.QIcon("demo.png"))
        it3 = QtWidgets.QListWidgetItem(self.listWidget)
        it3.setIcon(QtGui.QIcon("demo.png"))
        it4 = QtWidgets.QListWidgetItem(self.listWidget)
        it4.setIcon(QtGui.QIcon("demo.png"))
        it5 = QtWidgets.QListWidgetItem(self.listWidget)
        it5.setIcon(QtGui.QIcon("demo.png"))



        self.TEXT.raise_()
        self.imgLabel.raise_()
        self.NEXT_2.raise_()
        self.NEXT_4.raise_()
        self.NEXT_5.raise_()
        self.imgLabel_2.raise_()
        self.CAPTURE.raise_()
        self.NEXT_3.raise_()
        self.NEXT_7.raise_()
        self.checkBox_5.raise_()
        self.spinBox.raise_()
        self.listWidget.raise_()


        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CAPTURE.setText(_translate("Dialog", "Capture"))
        self.NEXT_2.setText(_translate("Dialog", "Chọn thiết bị"))
        self.NEXT_4.setText(_translate("Dialog", "Tùy chọn"))
        self.NEXT_5.setText(_translate("Dialog", "Thêm mới"))
        self.NEXT_3.setText(_translate("Dialog", "IN PHIẾU KHÁM"))
        self.NEXT_7.setText(_translate("Dialog", "Đóng"))
        self.checkBox_5.setText(_translate("Dialog", "Tự Động Chụp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
